### ISSUE TITLE
No install

### ISSUE THREAD

**Issue by adeleglise** [Technopathic/ReMark-Old#1]
Hi guys,

I've just installed ReMark, following instructions (https://github.com/Technopathic/ReMark/wiki/ReMark-Quick-Start)

There's no "install" in the remark folder, so I can't finish the installation.

I'm on Debian jessie, apache 2.4.10, mysql 5.5, php7, npm 6.

**Comment by Technopathic** [comment]
Hi there! Thanks for trying out ReMark. 

When you go to "http://yourwebsite/install", can you open your browser's developer console and show me a screenshot of any errors on that page? That would help greatly.

If you've moved the contents of the ReMark project folder to a different folder, be sure that the .env and the .bowerrc files were also moved with them. The .bowerrc file puts the bower_components folder in the correct folder when running 'bower install'.

**Comment by Technopathic** [comment]
Also, I just updated the Quick Start Guide to include another chmod requirement for JWT.

**Comment by adeleglise** [comment]
Hi !
Thanks for your answer.

Here is the screenshot, also i didn't move anything.

[https://lut.im/HMxWfck9uG/yNLwHfXzjETz8Hrm.PNG](url)

**Comment by Technopathic** [comment]
Console, please. (The next tab over in the developer tools). 
Can you also show me the file structure in your ReMark "public" folder?

**Comment by adeleglise** [comment]
It's part of the question i want to ask you : what the documentroot should be ?

I've tried with public/install, and it's not working either.

**Comment by Technopathic** [comment]
What is your current document root set to?
ReMark's server back-end is built with Laravel, so the virtual host config should be the same. Your document root and directory should be something like: "/myhome/myprojects/ReMark/public". 
This guide should explain it better: http://laravel-recipes.com/recipes/25/creating-an-apache-virtualhost

I did a quick Apache install without a virtual host. If you didn't create a virtual host for your ReMark app, then you should still be able to access it in your browser at: 'http://localhost/ReMark/public'

**Comment by adeleglise** [comment]
I've changed the virtualhost to serve /var/www/remark/public. It works.

Unfortunately I still cant access /install

**Comment by Technopathic** [comment]
Be sure that mod rewrite and mcrypt are enabled.

sudo a2enmod rewrite
php5enmod mcrypt

Then restart the apache2 service.

**Comment by adeleglise** [comment]
Hi,

I've activate the mod_rewrite for apache.

I'm using php7, so the command is phpenmod. I've activated the mcrypt module.

I still cant access "install". 

What I'm wondering is : where is the install file ? I've no install file inside the public folder.

**Comment by Technopathic** [comment]
The 'install.html' file is located in the 'ReMark/public/views/ folder.  It's routed by AngularJS, so it sounds like a front-end error. 
Try running 'bower install' again in the ReMark root with no errors are thrown and the bower_components folder is located in the 'ReMark/public' folder afterwards. I noticed some errors being thrown with moment.js yesterday, but it should be resolved now. 

If that doesn't work, show me the errors on the "Console" tab in the developer tools. 
![console](http://h4z.it/Image/963441_mark-install.PNG "Console")

**Comment by adeleglise** [comment]
Here is the content of ReMark root, and public folders : https://framabin.org/?f41811313c9f76f5#6jSD3zkg9q15RSBSmKDxGnN4d14y49tzRvP2NZsyYAw=
Here are the screenshot of the root site, and the /install : 
https://lut.im/60iT2j5rUP/wLGikb7Naki6SkoR.png
https://lut.im/8GM7XCvlCV/r0o37kqyCUMnpGcF.png

**Comment by Technopathic** [comment]
Just performed an installation with PHP7. 
Were there any errors via composer install? 
I've also updated the Quickstart Guide with a list of required PHP modules. You can check these modules using `php -m`.

**Comment by adeleglise** [comment]
composer install returns no error.

Here is the php -m output :

[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by Technopathic** [comment]
I haven't been able to replicate the issue, but it looks like index.php is not being accessed at all. Can you verify that the DirectoryIndex is set to index.php? 
Even if it's set to index.html, the .htaccess should redirect to index.php either way.

**Comment by adeleglise** [comment]
Here is the vhost, I've configured it with the less options I could :

https://framabin.org/?a265ee95299704b6#BUCs7Fy3qsO2D8B2GchvERuJU5eTbd9F+OUQDIC5jgc=

**Comment by adeleglise** [comment]
Hi,

do you have an idea on what is going on ?

**Comment by Technopathic** [comment]
I matched your versions and configs on a new server and didn't come up with a problem. 
Have you tried doing a standard Laravel installation and verifying the welcome page comes up correctly? 
That would help me pin down the problem.

**Comment by w00p** [comment]
Hi, i have something strange going on in the dashboard / content: take a looK. http://bildr.no/view/V3FTMTYw

Any idea why? When i install ReMark it ask me of what Angular version i want, what to choose?

**Comment by Technopathic** [comment]
@w00p 
I will look into the dashboard / Content page when I return home.

As for the Angular Version, when asked, you should install the latest Angular 1.x version. It will be the one that says "required by remark". 

The Angular 1.x front-end for ReMark will become depreciated soon as I move towards a React front-end.
